model_descriptions = {
    "low": "Быстрая модель, комбинация Edge-TTS для генерации речи и RVC для преобразования голоса. Низкие требования.",
    "low+": "Комбинация Silero TTS для генерации речи и RVC для преобразования голоса. Требования схожи с low.",
    "medium": "Модель Fish Speech для генерации речи с хорошим качеством. Требует больше ресурсов.",
    "medium+": "Скомпилированная на видеокарту версия Fish Speech. Требует больше места.",
    "medium+low": "Комбинация Fish Speech+ и RVC для высококачественного преобразования голоса.",
    "high": "Лучшая эмоциональная модель. Дифузионная модель, так что самая требовательная к видеокарте.",
    "high+low": "Лучшая эмоциональная модель. Дифузионная модель, так что самая требовательная к видеокарте."
}

model_descriptions_en = {
    "low": "Fast model; a combination of Edge-TTS for speech generation and RVC for voice conversion. Low requirements.",
    "low+": "Combination of Silero TTS for speech generation and RVC for voice conversion. Requirements similar to the 'low' model.",
    "medium": "Fish Speech model for speech generation with good quality. Requires more resources.",
    "medium+": "GPU-compiled version of Fish Speech. Requires more disk space.",
    "medium+low": "Combination of Fish Speech+ and RVC for high-quality voice conversion.",
    "high": "Best emotional model. A diffusion model, therefore the most GPU-demanding.",
    "high+low": "Best emotional model with RVC. A diffusion model, therefore the most GPU-demanding."
}

setting_descriptions = {
    "device": "Устройство для вычислений (GPU или CPU). 'cuda:0' - первая GPU NVIDIA, 'cpu' - центральный процессор, 'mps:0' - GPU Apple Silicon.",
    "pitch": "Изменение высоты голоса в полутонах. Положительные значения - выше, отрицательные - ниже. 0 - без изменений.",
    "is_half": "Использовать вычисления с половинной точностью (float16). Ускоряет работу на совместимых GPU (NVIDIA RTX и новее) и экономит видеопамять, может незначительно повлиять на качество.",
    "output_gain": "Усиление громкости финального аудиофайла. Значение 1.0 - без изменений, <1 тише, >1 громче. Полезно для нормализации громкости разных голосов.",
    "f0method": "[RVC] Алгоритм извлечения основного тона (F0). Определяет высоту голоса. 'rmvpe' и 'crepe' точные, но медленные. 'pm', 'harvest' быстрее. Влияет на естественность интонаций.",
    "use_index_file": "[RVC] Использовать файл .index для улучшения соответствия тембра голоса модели. Отключение может быть полезно, если индексный файл низкого качества или вызывает артефакты.",
    "index_rate": "[RVC] Степень использования индексного файла (.index) для сохранения тембра голоса RVC (0 до 1). Выше значение = больше похоже на голос из модели, но может добавить артефакты, если индекс некачественный.",
    "filter_radius": "[RVC] Радиус медианного фильтра для сглаживания кривой F0 (высоты тона). Убирает резкие скачки, делает речь более плавной. Рекомендуется значение >= 3.",
    "rms_mix_rate": "[RVC] Степень смешивания RMS (громкости) исходного аудио (из TTS/FSP) и результата RVC (0 до 1). 0 = полностью громкость RVC, 1 = полностью громкость оригинала. Помогает сохранить исходную динамику речи.",
    "protect": "[RVC] Защита глухих согласных (ш, щ, с, ...) от искажения высотой тона (0 до 0.5). Меньшие значения обеспечивают большую защиту (согласные звучат чище), но могут немного повлиять на интонацию гласных рядом. Рекомендуется 0.3-0.4.",
    "tts_rate": "[EdgeTTS] Изменение скорости речи базового синтезатора Edge-TTS (до RVC) в процентах. 0 - стандартная скорость.",
    "tts_volume": "[EdgeTTS] Изменение громкости речи базового синтезатора Edge-TTS (до RVC) в процентах. 0 - стандартная громкость.",
    
    "seed": "Сид для озвучки.",
    

    "silero_rvc_device": "Устройство для вычислений (GPU или CPU). 'cuda:0' - первая GPU NVIDIA, 'cpu' - центральный процессор, 'mps:0' - GPU Apple Silicon.",
    "silero_rvc_pitch": "Изменение высоты голоса в полутонах. Положительные значения - выше, отрицательные - ниже. 0 - без изменений.",
    "silero_rvc_is_half": "Использовать вычисления с половинной точностью (float16). Ускоряет работу на совместимых GPU (NVIDIA RTX и новее) и экономит видеопамять, может незначительно повлиять на качество.",
    "silero_rvc_output_gain": "Усиление громкости финального аудиофайла. Значение 1.0 - без изменений, <1 тише, >1 громче. Полезно для нормализации громкости разных голосов.",
    "silero_rvc_f0method": "[RVC] Алгоритм извлечения основного тона (F0). Определяет высоту голоса. 'rmvpe' и 'crepe' точные, но медленные. 'pm', 'harvest' быстрее. Влияет на естественность интонаций.",
    "silero_rvc_use_index_file": "[RVC] Использовать файл .index для улучшения соответствия тембра голоса модели. Отключение может быть полезно, если индексный файл низкого качества или вызывает артефакты.",
    "silero_rvc_index_rate": "[RVC] Степень использования индексного файла (.index) для сохранения тембра голоса RVC (0 до 1). Выше значение = больше похоже на голос из модели, но может добавить артефакты, если индекс некачественный.",
    "silero_rvc_filter_radius": "[RVC] Радиус медианного фильтра для сглаживания кривой F0 (высоты тона). Убирает резкие скачки, делает речь более плавной. Рекомендуется значение >= 3.",
    "silero_rvc_rms_mix_rate": "[RVC] Степень смешивания RMS (громкости) исходного аудио (из TTS/FSP) и результата RVC (0 до 1). 0 = полностью громкость RVC, 1 = полностью громкость оригинала. Помогает сохранить исходную динамику речи.",
    "silero_rvc_protect": "[RVC] Защита глухих согласных (ш, щ, с, ...) от искажения высотой тона (0 до 0.5). Меньшие значения обеспечивают большую защиту (согласные звучат чище), но могут немного повлиять на интонацию гласных рядом. Рекомендуется 0.3-0.4.",
    "tts_rate": "[EdgeTTS] Изменение скорости речи базового синтезатора Edge-TTS (до RVC) в процентах. 0 - стандартная скорость.",
    "tts_volume": "[EdgeTTS] Изменение громкости речи базового синтезатора Edge-TTS (до RVC) в процентах. 0 - стандартная громкость.",
    "silero_device": "[Silero] Устройство для генерации речи Silero (CPU или GPU).",
    "silero_sample_rate": "[Silero] Частота дискретизации для генерации речи Silero.", 
    "silero_put_accent": "[Silero] Автоматическая расстановка ударений.", 
    "silero_put_yo": "[Silero] Автоматическая замена 'е' на 'ё'.", 

    "half": "[FS/FSP] Использовать FP16 (половинную точность). Рекомендуется для скорости и экономии памяти на GPU.",
    "temperature": "[FS/FSP] Температура сэмплирования (>0). Контролирует случайность/разнообразие генерируемой речи. Выше = разнообразнее, но больше ошибок. Ниже = стабильнее.",
    "top_p": "[FS/FSP] Ядерное сэмплирование (Top-P, 0-1). Ограничивает выбор следующего токена только наиболее вероятными вариантами. Уменьшает вероятность генерации 'бреда'.",
    "repetition_penalty": "[FS/FSP] Штраф за повторение токенов (>1). Предотвращает зацикливание модели на одних и тех же словах/звуках. 1.0 - нет штрафа.",
    "chunk_length": "[FS/FSP] Размер чанка обработки текста (в токенах). Влияет на использование памяти и длину контекста, который модель 'видит' одновременно.",
    "max_new_tokens": "[FS/FSP] Максимальное количество генерируемых токенов за один шаг. Ограничивает длину аудиофрагмента, генерируемого за раз.",
    "compile_model": "[FSP] Использовать torch.compile() для JIT-компиляции модели. Значительно ускоряет выполнение на GPU после первого запуска, но требует доп. установки и время на компиляцию при старте.",
    "fsprvc_fsp_device": "[FSP+RVC][FSP] Устройство для части Fish Speech+.",
    "fsprvc_fsp_half": "[FSP+RVC][FSP] Half-precision для части Fish Speech+.",
    "fsprvc_fsp_temperature": "[FSP+RVC][FSP] Температура для части Fish Speech+.",
    "fsprvc_fsp_top_p": "[FSP+RVC][FSP] Top-P для части Fish Speech+.",
    "fsprvc_fsp_repetition_penalty": "[FSP+RVC][FSP] Штраф повторений для части Fish Speech+.",
    "fsprvc_fsp_chunk_length": "[FSP+RVC][FSP] Размер чанка для части Fish Speech+.",
    "fsprvc_fsp_max_tokens": "[FSP+RVC][FSP] Макс. токены для части Fish Speech+.",
    "fsprvc_fsp_seed": "[FSP+RVC][FSP] Сид для озвучки.",
    "fsprvc_rvc_device": "[FSP+RVC][RVC] Устройство для части RVC.",
    "fsprvc_is_half": "[FSP+RVC][RVC] Half-precision для части RVC.",
    "fsprvc_f0method": "[FSP+RVC][RVC] Метод F0 для части RVC.",
    "fsprvc_rvc_pitch": "[FSP+RVC][RVC] Высота голоса для части RVC.",
    "fsprvc_use_index_file": "[FSP+RVC][RVC] Использовать файл .index для улучшения соответствия тембра голоса модели. Отключение может быть полезно, если индексный файл низкого качества или вызывает артефакты.",
    "fsprvc_index_rate": "[FSP+RVC][RVC] Соотношение индекса для части RVC.",
    "fsprvc_protect": "[FSP+RVC][RVC] Защита согласных для части RVC.",
    "fsprvc_output_gain": "[FSP+RVC][RVC] Громкость (gain) для части RVC.",
    "fsprvc_filter_radius": "[FSP+RVC][RVC] Радиус фильтра F0 для части RVC.",
    "fsprvc_rvc_rms_mix_rate": "[FSP+RVC][RVC] Смешивание RMS для части RVC.",


    "speed": "[F5-TTS] Скорость генерируемой речи. 1.0 - нормальная скорость, >1.0 - быстрее, <1.0 - медленнее.",
    "remove_silence": "[F5-TTS] Автоматически удалять тишину в начале и конце сгенерированного аудио.",
    "nfe_step": "[F5-TTS] Количество шагов диффузии. Больше = лучше качество, но медленнее. Меньше = быстрее, но может быть хуже. (Рекомендуется: 3-10)",
    "cfg_strength": "[F5-TTS] Сила бесклассификаторного управления (CFG). Контролирует, насколько сильно генерация следует за референсным аудио. 0 - отключено. (Рекомендуется: 0.7)",
    "sway_sampling_coef": "[F5-TTS] Коэффициент сэмплирования 'Sway'. Добавляет вариативности в генерацию. 0 - отключено. (Рекомендуется: 0.0)",
    "target_rms": "[F5-TTS] Целевая громкость (RMS) для нормализации аудио. -1 отключает нормализацию. (Рекомендуется: -1)",
    "cross_fade_duration": "[F5-TTS] Длительность кроссфейда (в секундах) между аудио-чанками. (Рекомендуется: 0.015)",
    "fix_duration": "[F5-TTS] Фиксировать длительность фонем. Может улучшить стабильность, но снизить естественность. (Рекомендуется: False)",

    "f5rvc_f5_device": "[F5+RVC][F5] Устройство для части F5-TTS.",
    "f5rvc_f5_speed": "[F5+RVC][F5] Скорость речи для части F5-TTS.",
    "f5rvc_f5_nfe_step": "[F5+RVC][F5] Количество шагов диффузии для части F5-TTS.",
    "f5rvc_f5_remove_silence": "[F5+RVC][F5] Удаление тишины для части F5-TTS.",
    "f5rvc_f5_seed": "[F5+RVC][F5] Сид для озвучки.",
    "f5rvc_rvc_pitch": "[F5+RVC][RVC] Высота голоса для части RVC.",
    "f5rvc_index_rate": "[F5+RVC][RVC] Соотношение индекса для части RVC.",
    "f5rvc_protect": "[F5+RVC][RVC] Защита согласных для части RVC.",
    "f5rvc_filter_radius": "[F5+RVC][RVC] Радиус фильтра F0 для части RVC.",
    "f5rvc_rvc_rms_mix_rate": "[F5+RVC][RVC] Смешивание RMS для части RVC.",
    "f5rvc_is_half": "[F5+RVC][RVC] Half-precision для части RVC.",
    "f5rvc_f0method": "[F5+RVC][RVC] Метод F0 для части RVC.",
    "f5rvc_use_index_file": "[F5+RVC][RVC] Использовать файл .index для улучшения соответствия тембра голоса модели.",

    "tmp_directory": "Папка для временных файлов, создаваемых в процессе работы (например, промежуточные аудиофайлы).",
    "verbose": "Включить вывод подробной отладочной информации в консоль для диагностики проблем.",
    "cuda_toolkit": "Наличие установленного CUDA Toolkit от NVIDIA. Необходимо для некоторых функций (например, torch.compile) и работы с GPU NVIDIA.",
    "windows_sdk": "Наличие установленного Windows SDK. Может требоваться для компиляции некоторых зависимостей Python.",

    "volume": "Громкость (volume) на выходе TTS-части (до RVC, если он есть). 1.0 – оригинальная громкость."
}

setting_descriptions_en = {
    "device": "Device for computation (GPU or CPU). 'cuda:0' - first NVIDIA GPU, 'cpu' - central processor, 'mps:0' - Apple Silicon GPU.",
    "pitch": "Voice pitch change in semitones. Positive values - higher, negative - lower. 0 - no change.",
    "is_half": "Use half-precision computations (float16). Speeds up work on compatible GPUs (NVIDIA RTX and newer) and saves VRAM, may slightly affect quality.",
    "output_gain": "Volume gain for the final audio file. Value 1.0 - no change, <1 quieter, >1 louder. Useful for normalizing the volume of different voices.",
    "f0method": "[RVC] Fundamental frequency (F0) extraction algorithm. Determines voice pitch. 'rmvpe' and 'crepe' are accurate but slow. 'pm', 'harvest' are faster. Affects the naturalness of intonations.",
    "use_index_file": "[RVC] Use the .index file to improve the model's voice timbre matching. Disabling may be useful if the index file is low quality or causes artifacts.",
    "index_rate": "[RVC] Degree of using the index file (.index) to preserve the RVC voice timbre (0 to 1). Higher value = more similar to the model's voice, but may add artifacts if the index is poor quality.",
    "filter_radius": "[RVC] Radius of the median filter for smoothing the F0 curve (pitch). Removes sharp jumps, makes speech smoother. Recommended value >= 3.",
    "rms_mix_rate": "[RVC] Degree of mixing RMS (volume) of the source audio (from TTS/FSP) and the RVC result (0 to 1). 0 = fully RVC volume, 1 = fully original volume. Helps preserve the original speech dynamics.",
    "protect": "[RVC] Protection of voiceless consonants (sh, shch, s, ...) from pitch distortion (0 to 0.5). Lower values provide more protection (consonants sound cleaner), but may slightly affect the intonation of nearby vowels. Recommended 0.3-0.4.",
    "tts_rate": "[EdgeTTS] Change the speech rate of the base Edge-TTS synthesizer (before RVC) in percent. 0 - standard speed.",
    "tts_volume": "[EdgeTTS] Change the speech volume of the base Edge-TTS synthesizer (before RVC) in percent. 0 - standard volume.",
    
    "silero_rvc_device": "Устройство для вычислений (GPU или CPU). 'cuda:0' - первая GPU NVIDIA, 'cpu' - центральный процессор, 'mps:0' - GPU Apple Silicon.",
    "silero_rvc_pitch": "Изменение высоты голоса в полутонах. Положительные значения - выше, отрицательные - ниже. 0 - без изменений.",
    "silero_rvc_is_half": "Использовать вычисления с половинной точностью (float16). Ускоряет работу на совместимых GPU (NVIDIA RTX и новее) и экономит видеопамять, может незначительно повлиять на качество.",
    "silero_rvc_output_gain": "Усиление громкости финального аудиофайла. Значение 1.0 - без изменений, <1 тише, >1 громче. Полезно для нормализации громкости разных голосов.",
    "silero_rvc_f0method": "[RVC] Алгоритм извлечения основного тона (F0). Определяет высоту голоса. 'rmvpe' и 'crepe' точные, но медленные. 'pm', 'harvest' быстрее. Влияет на естественность интонаций.",
    "silero_rvc_use_index_file": "[RVC] Использовать файл .index для улучшения соответствия тембра голоса модели. Отключение может быть полезно, если индексный файл низкого качества или вызывает артефакты.",
    "silero_rvc_index_rate": "[RVC] Степень использования индексного файла (.index) для сохранения тембра голоса RVC (0 до 1). Выше значение = больше похоже на голос из модели, но может добавить артефакты, если индекс некачественный.",
    "silero_rvc_filter_radius": "[RVC] Радиус медианного фильтра для сглаживания кривой F0 (высоты тона). Убирает резкие скачки, делает речь более плавной. Рекомендуется значение >= 3.",
    "silero_rvc_rms_mix_rate": "[RVC] Степень смешивания RMS (громкости) исходного аудио (из TTS/FSP) и результата RVC (0 до 1). 0 = полностью громкость RVC, 1 = полностью громкость оригинала. Помогает сохранить исходную динамику речи.",
    "silero_rvc_protect": "[RVC] Защита глухих согласных (ш, щ, с, ...) от искажения высотой тона (0 до 0.5). Меньшие значения обеспечивают большую защиту (согласные звучат чище), но могут немного повлиять на интонацию гласных рядом. Рекомендуется 0.3-0.4.",
    "silero_rvc_tts_rate": "[EdgeTTS] Изменение скорости речи базового синтезатора Edge-TTS (до RVC) в процентах. 0 - стандартная скорость.",
    "silero_rvc_tts_volume": "[EdgeTTS] Изменение громкости речи базового синтезатора Edge-TTS (до RVC) в процентах. 0 - стандартная громкость.",
    

    "silero_device": "[Silero] Device for Silero speech generation (CPU or GPU).",
    "silero_sample_rate": "[Silero] Sample rate for Silero speech generation.",
    "silero_put_accent": "[Silero] Automatic stress placement.",
    "silero_put_yo": "[Silero] Automatic replacement of 'e' with 'yo'.",

    "half": "[FS/FSP] Use FP16 (half-precision). Recommended for speed and memory saving on GPU.",
    "temperature": "[FS/FSP] Sampling temperature (>0). Controls the randomness/diversity of generated speech. Higher = more diverse, but more errors. Lower = more stable.",
    "top_p": "[FS/FSP] Nucleus sampling (Top-P, 0-1). Limits the choice of the next token to only the most likely options. Reduces the probability of generating 'nonsense'.",
    "repetition_penalty": "[FS/FSP] Penalty for repeating tokens (>1). Prevents the model from looping on the same words/sounds. 1.0 - no penalty.",
    "chunk_length": "[FS/FSP] Text processing chunk size (in tokens). Affects memory usage and the length of the context the model 'sees' simultaneously.",
    "max_new_tokens": "[FS/FSP] Maximum number of generated tokens per step. Limits the length of the audio fragment generated at once.",
    "compile_model": "[FSP] Use torch.compile() for JIT compilation of the model. Significantly speeds up execution on GPU after the first run, but requires additional installation and compilation time at startup.",
    "fsprvc_fsp_device": "[FSP+RVC][FSP] Device for the Fish Speech+ part.",
    "fsprvc_fsp_half": "[FSP+RVC][FSP] Half-precision for the Fish Speech+ part.",
    "fsprvc_fsp_temperature": "[FSP+RVC][FSP] Temperature for the Fish Speech+ part.",
    "fsprvc_fsp_top_p": "[FSP+RVC][FSP] Top-P for the Fish Speech+ part.",
    "fsprvc_fsp_repetition_penalty": "[FSP+RVC][FSP] Repetition penalty for the Fish Speech+ part.",
    "fsprvc_fsp_chunk_length": "[FSP+RVC][FSP] Chunk size for the Fish Speech+ part.",
    "fsprvc_fsp_max_tokens": "[FSP+RVC][FSP] Max tokens for the Fish Speech+ part.",
    "fsprvc_rvc_device": "[FSP+RVC][RVC] Device for the RVC part.",
    "fsprvc_is_half": "[FSP+RVC][RVC] Half-precision for the RVC part.",
    "fsprvc_f0method": "[FSP+RVC][RVC] F0 method for the RVC part.",
    "fsprvc_rvc_pitch": "[FSP+RVC][RVC] Voice pitch for the RVC part.",
    "fsprvc_use_index_file": "[FSP+RVC][RVC] Use the .index file to improve the model's voice timbre matching. Disabling may be useful if the index file is low quality or causes artifacts.",
    "fsprvc_index_rate": "[FSP+RVC][RVC] Index rate for the RVC part.",
    "fsprvc_protect": "[FSP+RVC][RVC] Consonant protection for the RVC part.",
    "fsprvc_output_gain": "[FSP+RVC][RVC] Volume (gain) for the RVC part.",
    "fsprvc_filter_radius": "[FSP+RVC][RVC] F0 filter radius for the RVC part.",
    "fsprvc_rvc_rms_mix_rate": "[FSP+RVC][RVC] RMS mixing for the RVC part.",

    "speed": "[F5-TTS] Speed of the generated speech. 1.0 is normal speed, >1.0 is faster, <1.0 is slower.",
    "remove_silence": "[F5-TTS] Automatically remove silence from the beginning and end of the generated audio.",
    "nfe_step": "[F5-TTS] Number of diffusion steps. More = better quality, but slower. Less = faster, but may be worse. (Recommended: 3-10)",
    "cfg_strength": "[F5-TTS] Classifier-Free Guidance (CFG) strength. Controls how strongly the generation follows the reference audio. 0 - disabled. (Recommended: 0.7)",
    "sway_sampling_coef": "[F5-TTS] 'Sway' sampling coefficient. Adds variability to the generation. 0 - disabled. (Recommended: 0.0)",
    "target_rms": "[F5-TTS] Target loudness (RMS) for audio normalization. -1 disables normalization. (Recommended: -1)",
    "cross_fade_duration": "[F5-TTS] Crossfade duration (in seconds) between audio chunks. (Recommended: 0.015)",
    "fix_duration": "[F5-TTS] Fix phoneme duration. May improve stability but reduce naturalness. (Recommended: False)",

    "f5rvc_f5_device": "[F5+RVC][F5] Device for the F5-TTS part.",
    "f5rvc_f5_speed": "[F5+RVC][F5] Speech speed for the F5-TTS part.",
    "f5rvc_f5_nfe_step": "[F5+RVC][F5] Diffusion steps for the F5-TTS part.",
    "f5rvc_f5_remove_silence": "[F5+RVC][F5] Remove silence for the F5-TTS part.",
    "f5rvc_rvc_pitch": "[F5+RVC][RVC] Voice pitch for the RVC part.",
    "f5rvc_index_rate": "[F5+RVC][RVC] Index rate for the RVC part.",
    "f5rvc_protect": "[F5+RVC][RVC] Consonant protection for the RVC part.",
    "f5rvc_filter_radius": "[F5+RVC][RVC] F0 filter radius for the RVC part.",
    "f5rvc_rvc_rms_mix_rate": "[F5+RVC][RVC] RMS mixing for the RVC part.",
    "f5rvc_is_half": "[F5+RVC][RVC] Half-precision for the RVC part.",
    "f5rvc_f0method": "[F5+RVC][RVC] F0 method for the RVC part.",
    "f5rvc_use_index_file": "[F5+RVC][RVC] Use the .index file to improve the model's voice timbre matching.",

    "tmp_directory": "Folder for temporary files created during operation (e.g., intermediate audio files).",
    "verbose": "Enable detailed debug information output to the console for diagnosing problems.",
    "cuda_toolkit": "Presence of installed NVIDIA CUDA Toolkit. Required for some functions (e.g., torch.compile) and working with NVIDIA GPUs.",
    "windows_sdk": "Presence of installed Windows SDK. May be required for compiling some Python dependencies.",

    "volume": "Output loudness (volume). 1.0 – original volume. "
}

default_description_text = "Наведите курсор на элемент интерфейса для получения описания."
default_description_text_en = "Hover over an interface element to get a description."